### ISSUE TITLE
Usage Questions:

### ISSUE THREAD

**Issue by mickdelaney** [WebApiContrib/CollectionJson.Net#112]
I've read a fair amount about rest/hypermedia but i'm trying to understand the specific usage of CollectionJson. 

In particular the "Data" item that you return in the Collection. As it stands its only used for Key value pairs of strings. But what about if you have an object?? say one of my 'Data' items is a List of a Key Value pair for example. 

And also what about other top level data items, such as lists. 
For example I'm building a search page, which has as top level items, 'Facets' & 'Results'. 
How would that fit in to CollectionJson or am I just using the wrong media type ??

regards

**Comment by pedroreys** [comment]
I'm afraid Collection+JSON might not be the best media type for what you are trying to do.

Per the current version of the [Collection+JSON spec](http://amundsen.com/media-types/collection/format/), a `data` element [is defined as](http://amundsen.com/media-types/collection/format/#arrays-data):

>data
>The data array is a child property of the items array and the template object.
>
>The data array SHOULD contain one or more anonymous objects. Each object is MAY have any of three possible properties: name (REQUIRED), value (OPTIONAL), and prompt (OPTIONAL).
>
````javascript
// sample data array
{
  "template" :
  {
    "data" :
    [
      {"prompt" : STRING, "name" : STRING, "value" : VALUE},
      {"prompt" : STRING, "name" : STRING, "value" : VALUE},
      ...
      {"prompt" : STRING, "name" : STRING, "value" : VALUE}
    ]
  }
}
````

Note that the `value` property is defined with the data type `VALUE`, that [is defined as](http://amundsen.com/media-types/collection/format/#type-value):

> 7.6. VALUE
>A VALUE data type MUST be a NUMBER, STRING, or one of the following literal names: false, null, or true.
>
>NOTE: This release of Collection+JSON does not support OBJECT or ARRAY as a valid VALUE.

**Comment by gabrewer** [comment]
There is a suggested extension that would include arrays and objects in the data element.

https://github.com/collection-json/extensions/blob/master/value-types.md

**Comment by glennblock** [comment]
Sorry for the late reply.

it's true the CJ really is not designed for nested objects. This is one of
the design goals of Uber (https://github.com/uber-hypermedia/) which
supports arbitrary nesting. I also have a small Uber.NET lib (
https://github.com/glennblock/uberhypermedia.net) if you want to try it out.

One thing I'd suggest is to join the CJ google mailing list. There's a lot
of good discussion there and this has been a hot topic with a few suggested
approaches. Here's ones that i remember

1. You can have compound keys (I've used this) like "item[1].data".
2. You can have heterogeneous collections with items that link to each
other. For example you can have a parent item with an href to a child item
in the collection.

The value-types extension (imo) doesn't seem ideal as it is really oriented
toward values of items being a collection, but those values are still
scalar / not objects.

Uber might better suit your need. Also looser types like HAL also could be
an option.


Cheers
Glenn
