### ISSUE TITLE
Missing nuget dependency on DynamicUtils

### ISSUE THREAD

**Issue by darrelmiller** [WebApiContrib/CollectionJson.Net#113]

**Comment by glennblock** [comment]
Oh shoot. Will get on this tonight unless you want to send a PR :-)

**Comment by darrelmiller** [comment]
I should be able to send a PR soon.  In car currently  though. 😊

Darrel

Sent from my Windows Phone
________________________________

**Comment by thomaseyde** [comment]
The dependency is still missing :-(
