### ISSUE TITLE
CollectionJsonController Initialize modifies global WebApi configuration

### ISSUE THREAD

**Issue by Shazwazza** [WebApiContrib/CollectionJson.Net#116]
In the CollectionJsonController Initialize method it is modifying the controllerContext.Configuration.Formatters which is actually going to be modifying the Global configuration for all controllers. For per-controller configuration you need to use IControllerConfiguration with a custom attribute like:

    /// <summary>
    /// Applying this attribute to any webapi controller will ensure that the CollectionJsonFormatter is added to the controller
    /// </summary>
    public class CollectionJsonFormatterConfigurationAttribute : Attribute, IControllerConfiguration
    {
        public virtual void Initialize(HttpControllerSettings controllerSettings, HttpControllerDescriptor controllerDescriptor)
        {
            controllerSettings.Formatters.Insert(0, new CollectionJson.Client.CollectionJsonFormatter());
        }
    }

I could be mistaken if something has changed in WebApi 2 but that is certainly the case with WebApi1

**Comment by glennblock** [comment]
@Shazwazza I believe in WebApi 2 this only modifies for this controller. @darrelmiller?

**Comment by Shazwazza** [comment]
Yup, i've confirmed in webapi 2 it only mods the controller instances config which is great!
