### ISSUE TITLE
support for "error" object

### ISSUE THREAD

**Issue by Shazwazza** [WebApiContrib/CollectionJson.Net#117]
this is part of the collection+json spec:

http://amundsen.com/media-types/collection/format/

under: **3.2. error** heading

**Comment by glennblock** [comment]
Hi @Shazwazza it is there: https://github.com/WebApiContrib/CollectionJson.Net/blob/master/src/CollectionJson/Error.cs

What are you looking for exactly?

**Comment by glennblock** [comment]
@Shazwazza wait you mean I don't expose it on the Collection?

**Comment by Shazwazza** [comment]
Yup, the Collection doesn't expose it. Of course that's easy to get around by just dynamically creating that property but would be good to have it strongly typed

**Comment by glennblock** [comment]
Makes sense. Will fix, or I would welcome a PR :-)
